### ISSUE TITLE
Add RPM SPEC app description

### ISSUE THREAD

**Issue by rinigus** [attah/harbour-thermalcam#1]
Currently description is "Short description of my Sailfish OS Application". Please change it to describe the app :)

**Comment by attah** [comment]
Right.. that's the proper place for descriptions. Never really had use of that before. Fixed.
Sneakily moved the tag too. I will refrain form that once published.

**Comment by attah** [comment]
Oh crap. It was accepted... i just have no idea how to navigate OBS. :)

**Comment by rinigus** [comment]
No problem - it was accepted as everything else was in order .  Accepted revision as well. When ready, submit to chum from its testing version

**Comment by attah** [comment]
Done. I'm not sure i'll do much more to it until i have users, or figure out that i need something.
